---
- hosts: all
  become: true
  
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
  
  - name: Install network tools
    apt:
      name: net-tools
      state: present
  
  - name: Check nginx version 
    command: sudo nginx -v
    register: nginx_version
  - debug:
      var: nginx_version.stderr
  



