---
- hosts: all
  become: true

  vars:
    linux_distribution: ubuntu
  
  tasks:
  - name: Update all packages (centos)
    yum:
      name: '*'
      state: latest
      update_only: yes
    when: linux_distribution == "centos"
  
  - name: Ensure a list of yum packages are installed (centos)
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - yum-utils
      - amazon-linux-extras
    when: linux_distribution == "centos"
  
  - name: Add extras repository (centos)
    shell: yum-config-manager --enable extras
    when: linux_distribution == "centos"

  - name: Install nginx (centos)
    shell: amazon-linux-extras install nginx1.12=latest -y
    when: linux_distribution == "centos"
    notify:
      - Enable Nginx service at startup
  
  - name: Install Network tools (centos)
    yum:
      name: net-tools.x86_64
      state: latest
      update_cache: yes
    when: linux_distribution == "centos"
      
  - name: Install nginx (ubuntu)
    apt:
      name: nginx
      state: present
    when: linux_distribution == "ubuntu"
  
  - name: Install network tools (ubuntu)
    apt:
      name: net-tools
      state: present
    when: linux_distribution == "ubuntu"
  
  - name: Check nginx version 
    command: sudo nginx -v
    register: nginx_version
  - debug:
      var: nginx_version.stderr
  
  - name: Check nginx service status
    service_facts:
    register: services_state
  - debug:
      var: services_state.ansible_facts.services['nginx.service']
  
  handlers:
  - name: Enable Nginx service at startup
    service:
      name: nginx
      state: started
      enabled: yes
    when: nginx_version.changed == true
